accounts/urls.py
from django.urls import path
from .views import RegisterBuyerView, LogoutBuyerView, LoginBuyerView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterBuyerView.as_view(), name='register'),
    path('logout/', LogoutBuyerView.as_view(), name='logout'),
    path('login/', LoginBuyerView.as_view(), name='login'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('products.urls'))
]

products/urls.py
from django.urls import path
from .views import HomeView

app_name = 'products'

urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Buyer(AbstractUser):
    country = models.CharField(null=True, blank=True, max_length=30)
    city = models.CharField(null=True, blank=True, max_length=30)
    region = models.CharField(null=True, blank=True, max_length=30)
    address = models.CharField(null=True, blank=True, max_length=30)
    postal_code = models.CharField(null=True, blank=True, max_length=30)
    number_phone = models.CharField(null=True, blank=True, max_length=30)

    class Meta:
        verbose_name_plural = 'Buyer'

    def __str__(self) -> str:
        return self.username

products/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from .models import Buyer


class RegisterBuyerForm(forms.ModelForm):
    username = forms.TextInput()
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Ingrese su contraseña')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Confirme su contraseña')

    class Meta:
        model = Buyer
        fields = ['username', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'})
        }
        labels = {
            'username': 'Ingrese su nombre de usuario',
        }


class LoginBuyerForm(forms.ModelForm):
    username = forms.TextInput()
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Ingrese su contraseña')

    class Meta:
        model = Buyer
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'})
        }
        labels = {
            'username': 'Ingrese su nombre de usuario',
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import RegisterBuyerForm, LoginBuyerForm
from .models import Buyer


class RegisterBuyerView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'accounts/register.html'
        form = RegisterBuyerForm()
        context = {
            'form': form
        }

        return render(request, template_name, context)

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            if request.POST['password1'] == request.POST['password2']:
                form = RegisterBuyerForm(request.POST)
                if form.is_valid():
                    buyer = Buyer.objects.create_user(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
                    buyer.save()
                    login(request, buyer)

                    return redirect('products:home')
                else:
                    for msg in form.errors:
                        messages.error(request, form.errors[msg])

                    context = {
                        'form': form
                    }

                    return render(request, 'accounts/register.html', context)
            else:
                form = RegisterBuyerForm()
                context = {
                    'form': form,
                    'error': 'Sus contraseñas no son iguales'
                }

                return render(request, 'accounts/register.html', context)


class LogoutBuyerView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('products:home')


class LoginBuyerView(View):
    def get(self, request, *args, **kwargs):
        form = LoginBuyerForm()
        context = {
            'form': form,
        }

        return render(request, 'accounts/login.html', context)

    def post(self, request, *args, **kwargs):
        form = LoginBuyerForm()
        if request.method == 'POST':
            buyer = authenticate(request, username=request.POST['username'], password=request.POST['password'])

            if buyer is None:
                context = {
                    'form': form,
                    'error': 'Usuario o contraseña incorrecto'
                }

                return render(request, 'accounts/login.html', context)
            else:
                login(request, buyer)
                return redirect('products:home')

products/views.py
from django.shortcuts import render, redirect
from django.views.generic import View


class HomeView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'products/index.html'
        context = {}

        return render(request, template_name, context)

templates/accounts/login.html
{% extends "../base.html" %}

{% block content %}

Iniciar sesion

<form method="post" class="container">
    {% csrf_token %}

    <span class="list-group-item list-group-item-danger">{{ error | escape }}</span>


    {% for field in form %}

    <label for="{{ field.auto_id }}" class="form-label">{{ field.label }}</label>
    {{ field }}

    {% endfor %}

    <button class="btn btn-primary">Iniciar sesion</button>

</form>

{% endblock %}

templates/accounts/register.html
{% extends "../base.html" %}

{% block content %}

Registrarse

<form method="post" class="container">
    {% csrf_token %}

    {% if form.errors %}
    {% for field in form %}
    {% if field.errors %}
    {% for error in field.errors %}
    <span class="list-group-item list-group-item-danger">{{ error | escape }}</span>
    {% endfor %}
    {% endif %}
    {% endfor %}
    {% endif %}

    <span class="list-group-item list-group-item-danger">{{ error | escape }}</span>

    {% for field in form %}

    <label for="{{ field.auto_id }}" class="form-label">{{ field.label }}</label>
    {{ field }}

    {% endfor %}

    <button class="btn btn-primary">Crear usuario</button>

</form>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <title>Ecommerce Final</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Ecommerce</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Productos</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Cerrar sesion</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">Registrarse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Iniciar sesion</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="cont-sh">
                <form class="d-flex search-form">
                    <input class="form-control me-2" type="search" placeholder="Escriba el producto a buscar"
                        aria-label="Search" />
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>

                <a href="#" class="btn btn-outline-primary btn-search"><i class="fas fa-shopping-cart"></i> </a>
            </div>
        </div>
    </nav>

    {% block content %} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
</body>

</html>

templates/products/index.html
{% extends "../base.html" %}

{% block content %}

Hello

{% endblock %}